# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20150602_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name_plural': 'Work Orders'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 4, 3, 3, 57, 696937, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 4, 3, 4, 2, 665719, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
